version: '3.8'
services:
  xnat-web:
    build:
      context: ./xnat
      args:
        XNAT_VERSION: ${XNAT_VERSION}
        XNAT_SMTP_ENABLED: ${XNAT_SMTP_ENABLED}
        XNAT_SMTP_HOSTNAME: ${XNAT_SMTP_HOSTNAME}
        XNAT_SMTP_PORT: ${XNAT_SMTP_PORT}
        XNAT_SMTP_AUTH: ${XNAT_SMTP_AUTH}
        XNAT_SMTP_USERNAME: ${XNAT_SMTP_USERNAME}
        XNAT_SMTP_PASSWORD: ${XNAT_SMTP_PASSWORD}
        XNAT_DATASOURCE_DRIVER: ${XNAT_DATASOURCE_DRIVER}
        XNAT_DATASOURCE_URL: ${XNAT_DATASOURCE_URL}
        XNAT_DATASOURCE_USERNAME: ${XNAT_DATASOURCE_USERNAME}
        XNAT_DATASOURCE_PASSWORD: ${XNAT_DATASOURCE_PASSWORD}
        TOMCAT_XNAT_FOLDER: ${TOMCAT_XNAT_FOLDER}
        XNAT_ROOT: ${XNAT_ROOT}
        XNAT_HOME: ${XNAT_HOME}
        XNAT_EMAIL: ${XNAT_EMAIL}
        XNAT_LDAP_AMC_ENABLED: ${XNAT_LDAP_AMC_ENABLED}
        XNAT_LDAP_AMC_HOSTNAME: ${XNAT_LDAP_AMC_HOSTNAME}
        XNAT_LDAP_AMC_PROVIDER_ID: ${XNAT_LDAP_AMC_PROVIDER_ID}
        XNAT_LDAP_AMC_VISIBLE: ${XNAT_LDAP_AMC_VISIBLE}
        XNAT_LDAP_AMC_AUTO_ENABLED: ${XNAT_LDAP_AMC_AUTO_ENABLED}
        XNAT_LDAP_AMC_AUTO_VERIFIED: ${XNAT_LDAP_AMC_AUTO_VERIFIED}
        XNAT_LDAP_AMC_ADDRESS: ${XNAT_LDAP_AMC_ADDRESS}
        XNAT_LDAP_AMC_USERDN: ${XNAT_LDAP_AMC_USERDN}
        XNAT_LDAP_AMC_PASSWORD: ${XNAT_LDAP_AMC_PASSWORD}
        XNAT_LDAP_AMC_SEARCH_BASE: ${XNAT_LDAP_AMC_SEARCH_BASE}
        XNAT_LDAP_AMC_SEARCH_FILTER: ${XNAT_LDAP_AMC_SEARCH_FILTER}

    ports:
      - 8104:8104
      - 8080:8080
    volumes:
      - ${XNAT_HOME_AT_HOST}/plugins:/data/xnat/home/plugins
      - ${XNAT_HOME_AT_HOST}/logs:/data/xnat/home/logs
      - ${XNAT_DATA_AT_HOST}/archive:${XNAT_ROOT}/archive
      - ${XNAT_HOME_AT_HOST}/build:${XNAT_ROOT}/build
      - ${XNAT_HOME_AT_HOST}/cache:${XNAT_ROOT}/cache
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms${XNAT_MIN_HEAP} -Xmx${XNAT_MAX_HEAP} -Dxnat.home=${XNAT_HOME}
      - XNAT_HOME_AT_HOST=${XNAT_HOME}
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost"]
#      interval: 1m
#      timeout: 10s
#      retries: 3
#      start_period: 40s

  xnat-db:
    image: postgres:${PG_VERSION}
    expose:
      - "5432"
    volumes:
      - ${XNAT_HOME_AT_HOST}/postgresql-data:/var/lib/postgresql/data
      # 
      - ${XNAT_HOME_AT_HOST}/postgresql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${XNAT_DATASOURCE_ADMIN_PASSWORD}
      - POSTGRES_DB=${XNAT_DATASOURCE_NAME}
      # variables for the sql script
      - XNAT_DATASOURCE_USERNAME=${XNAT_DATASOURCE_USERNAME}
      - XNAT_DATASOURCE_PASSWORD=${XNAT_DATASOURCE_PASSWORD}

